name: Lint Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: Oxlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oxc-project/oxlint-action@f95bba5b65244df9bd7f5106494a7ef1fd44f22e
        with:
          config: .oxlintrc.json
          all-files: true
          working-directory: resources/scripts
